In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
# DN = 'C://work/dev/python/progs/texts/attack_classifier/'
DN = '/home/jovyan/work/sec_bert/'

import os
os.chdir(DN)

In [3]:
import warnings
warnings.filterwarnings('ignore')

# train

В функции get_opt_thresh src/funcs.py добавил переменную fpr_max, которая управляет долей ложноположительных ответов, сейчас на 10% стоит (fpr_max = 0.1), так выдает очень много вариантов. Можно поменять прям в коде этудолю и перезапустить обучение путем выполнения ячейки с train.

In [ ]:
from src.train import train

train()

Some weights of RobertaModel were not initialized from the model checkpoint at data/external/models/SecureBERT_Plus/snapshots/4c48ccdb8d2019f179b07dfa27656c655394d78e and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

epoch num - 1
epoch num - 2
epoch num - 3
epoch num - 4
epoch num - 5
epoch num - 6

## pred

In [ ]:
from src.predict import predict

pred_df = predict([
    'APT32 compromised McAfee ePO to move laterally by distributing malware as a software deployment task.', 
    'Monitor executed commands and arguments that may indicate common cryptomining or proxyware functionality.', 
    'TeamTNT has created system services to execute cryptocurrency mining software',
    'An adversary may abuse configurations where an application has the setuid or setgid bits set in order to get code running in a different (and possibly more privileged) user’s context',
    'Service execution was also widely used and is discussed in depth in the lateral movement section',
    'loader mimicked the legitimate Microsoft Windows Media Configuration Utility',
    'administrative privileges were leveraged during the lateral movement to execute a PowerShell-based Cobalt Strike payload',
    'utilized a \'Run\' key in the Windows registry to enable the automatic execution of a GhostSOCKS payload',
    'threat actor created several persistent backdoors in the environment using scheduled tasks',
    'intrusion began with the download and execution of a Cobalt Strike beacon that impersonated a Windows Media Configuration Utility',
    'access critical system resources, including the LSASS memory space',
    'then the malware connects to C2 servers to transfer data.'
])
pred_df

In [5]:
from src.predict import predict

pred_df = predict([
    'APT32 compromised McAfee ePO to move laterally by distributing malware as a software deployment task.', 
    'Monitor executed commands and arguments that may indicate common cryptomining or proxyware functionality.', 
    'TeamTNT has created system services to execute cryptocurrency mining software',
    'An adversary may abuse configurations where an application has the setuid or setgid bits set in order to get code running in a different (and possibly more privileged) user’s context',
    'Service execution was also widely used and is discussed in depth in the lateral movement section',
    'loader mimicked the legitimate Microsoft Windows Media Configuration Utility',
    'administrative privileges were leveraged during the lateral movement to execute a PowerShell-based Cobalt Strike payload',
    'utilized a \'Run\' key in the Windows registry to enable the automatic execution of a GhostSOCKS payload',
    'threat actor created several persistent backdoors in the environment using scheduled tasks',
    'intrusion began with the download and execution of a Cobalt Strike beacon that impersonated a Windows Media Configuration Utility',
    'access critical system resources, including the LSASS memory space',
    'then the malware connects to C2 servers to transfer data.'
])
pred_df

,sentence,target,proba_tak,pred_tak,proba_tech,pred_tech,pred_str_tech,pred_str_tak
0,APT32 compromised McAfee ePO to move laterally...,1,"[0.2338586300611496, 0.2423837035894394, 0.192...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[1.0375915735494345e-06, 6.501613825093955e-05...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","(T1072, T1219)",()
1,Monitor executed commands and arguments that m...,1,"[0.04887229576706886, 0.001607994781807065, 0....","[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]","[6.21709696133621e-05, 5.87736894885893e-06, 0...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",(),"(discovery,)"
2,TeamTNT has created system services to execute...,1,"[0.08446592092514038, 0.09254343807697296, 0.4...","[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]","[7.932241715025157e-06, 1.2068846444890369e-05...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","(T1543, T1569)","(execution, impact)"
3,An adversary may abuse configurations where an...,1,"[0.8765986561775208, 0.7844467759132385, 0.089...","[1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[1.3489462880045267e-08, 1.5700430594733916e-0...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","(T1546, T1548)","(defense-evasion, privilege-escalation)"
4,Service execution was also widely used and is ...,1,"[0.00154966174159199, 0.008930962532758713, 0....","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[4.267062081453332e-08, 0.0003662725503090769,...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",(),()
5,loader mimicked the legitimate Microsoft Windo...,1,"[0.5204117298126221, 0.008494787849485874, 0.0...","[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[6.022800880600698e-05, 1.8867174730985425e-05...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","(T1036,)","(defense-evasion,)"
6,administrative privileges were leveraged durin...,1,"[0.26033592224121094, 0.3431902229785919, 0.26...","[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[1.0024403529484971e-08, 0.0004605865688063204...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",(),"(defense-evasion,)"
7,utilized a 'Run' key in the Windows registry t...,1,"[0.41173526644706726, 0.8447058200836182, 0.26...","[1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[5.564768798649311e-06, 1.0679150364012457e-05...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","(T1547,)","(defense-evasion, privilege-escalation, persis..."
8,threat actor created several persistent backdo...,1,"[0.06131568178534508, 0.9572008848190308, 0.57...","[0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[1.712194602987438e-06, 9.057295756065287e-06,...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","(T1053,)","(privilege-escalation, execution, persistence)"
9,intrusion began with the download and executio...,1,"[0.21510590612888336, 0.02470245026051998, 0.3...","[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[1.1615293260547332e-05, 0.0002559153945185244...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","(T1219,)","(execution,)"
10,"access critical system resources, including th...",1,"[0.050980694591999054, 0.0109898392111063, 0.0...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[1.4347324395203032e-06, 0.10646920651197433, ...","[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","(T1003,)",()
11,then the malware connects to C2 servers to tra...,1,"[0.006618238985538483, 0.00012961821630597115,...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]","[8.624794281786308e-05, 5.3447784011950716e-05...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","(T1041,)","(exfiltration,)"

In [19]:
import pandas as pd

with pd.option_context('display.max_colwidth', 500):
    display(pd.read_json('data/temp/chatgpt_ttps.txt'))

,mitre_id,mitre_name,reason
0,T1204.002,Malicious File,intrusion began with the download and execution of a Cobalt Strike beacon that impersonated a Windows Media Configuration Utility
1,T1567.002,Exfiltration to Cloud Storage,they moved to using MEGA.io for data exfiltration
2,T1053.005,Scheduled Task,threat actor created several persistent backdoors in the environment using scheduled tasks
3,T1055,Process Injection,"utilized process injection techniques, such as injecting into WUAUCLT.exe"
4,T1569.002,Service Execution,service execution was also widely used and is discussed in depth in the lateral movement section
5,T1036,Masquerading,loader mimicked the legitimate Microsoft Windows Media Configuration Utility
6,T1087.002,Domain Account,attempted to use NTDSUtil via PowerShell remoting to extract credentials
7,T1059.001,PowerShell,administrative privileges were leveraged during the lateral movement to execute a PowerShell-based Cobalt Strike payload
8,T1562.001,Disable or Modify Tools,threat actor employed several methods to disable Windows Defender
9,T1021.002,SMB/Windows Admin Shares,utilized SMB to transfer tools such as the SystemBC DLL
10,T1547.001,Registry Run Keys / Startup Folder,utilized a 'Run' key in the Windows registry to enable the automatic execution of a GhostSOCKS payload
11,T1047,Windows Management Instrumentation,command shown below utilizes WMIC to remotely create a process
12,T1486,Data Encrypted for Impact,LockBit ransomware was deployed across the environment
13,T1003.001,LSASS Memory,"access critical system resources, including the LSASS memory space"

# Делаем прогнозы на всем датасете (чтобы получить метрики по количеству случаев с той же границей)

In [7]:
import joblib
from ruamel.yaml import YAML

import numpy as np

conf = YAML().load(open('params.yaml'))

mlb = joblib.load(conf['prep_text']['mlb_fn'])
mlb_ttp = joblib.load(conf['prep_text']['ttp_mlb_fn'])

thresh_tech_l = joblib.load(conf['train_fin']['thresh_ttp_fn'])
thresh_tak_l = joblib.load(conf['train_fin']['thresh_fn'])

In [8]:
from src.train import load_external_data, enc_classes

conf = YAML().load(open('params.yaml'))
df = load_external_data(conf)
df, mlb, mlb_ttp = enc_classes(df, conf, use_rare_ttp=False)

In [9]:
from src.predict import predict

pred_main = predict(df['sentence'].to_numpy().tolist())
pred_main.head(2)

,sentence,target,proba_tak,pred_tak,proba_tech,pred_tech,pred_str_tech,pred_str_tak
0,Adversaries may inject malicious code into pro...,1,"[0.9159165024757385, 0.945948600769043, 0.0647...","[1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[3.096574118899298e-06, 0.0006365251028910279,...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","(T1055,)","(defense-evasion, privilege-escalation)"
1,"Before creating a window, graphical Windows-ba...",1,"[0.17777800559997559, 0.2613764703273773, 0.44...","[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[9.790064359549433e-05, 0.00014453123731072992...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","(T1546, T1559)","(execution,)"

In [10]:
pred_main = pred_main.assign(ttp=df['ttp'])

## посчитаем эмбеддинги

In [11]:
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

conf_ttp = YAML().load(open('dvc_pipes/ttp/params_ttp.yaml'))
conf_ttp['feat_gen'] = conf_ttp['feat_gen_ttp'] 
emb_path = conf_ttp['feat_gen']['aug_emb_path']

smodel = SentenceTransformer(emb_path)

In [12]:
pred_main['enc_sents'] = smodel.encode(pred_main['sentence'].to_numpy()).tolist()

## находим границы на заданном уровне ошибок

In [13]:
border_l = []
for i in range(len(mlb_ttp.classes_)):
    perc_x = 0.05
    border_l.append(pred_main['proba_tech'].map(lambda x: x[i]).quantile(1-perc_x))

# Исследование плохих прогнозов

In [15]:
import pandas as pd
ex_num = 10
row = pred_df.iloc[ex_num]

row['pred_str_tech']

('T1003',)

In [16]:
q_levels = []
for i, val in enumerate(row['proba_tech']):
    q_levels.append( ((pred_main['proba_tech'].map(lambda x: x[i]))>val).mean())

In [17]:
# датасет другой поэтому не все предсказывается

border_df = pd.DataFrame({'q_level':q_levels}).sort_values(by='q_level', ascending=True).assign(cls=lambda x: x.index.map(lambda i: mlb_ttp.classes_[i]))
border_df.head()

      q_level    cls
1    0.009767  T1003
36   0.021151  T1057
192  0.037969  T1611
9    0.054398  T1014
206  0.055433  T1652

## близость к целевому классу

In [18]:
ttp = 'T1003.001'
idx_cls = np.where(mlb_ttp.classes_==ttp)[0][0]
idx_cls

IndexError: index 0 is out of bounds for axis 0 with size 0

In [22]:
# реальная метрика
proba = row['proba_tech'][idx_cls]
proba

0.01818215660750866

In [23]:
# текущая граница
thresh_tech_l[idx_cls]

0.13196842253208194

In [25]:
# на заданном уровне граница 5%
border_l[idx_cls]

0.015257064811885355

## все близкие классы

### преодолевающие границу по всем классам

In [26]:
idx_cls = np.where(np.array(row['proba_tech'])>np.array(border_l))[0]
idx_cls

array([  5,  11, 112])

In [27]:
mlb_ttp.classes_[idx_cls]

array(['T1003.001', 'T1003.007', 'T1057'], dtype=object)

### просто близкие к классу

In [28]:
embeddings = smodel.encode([row['sentence']])
sims = cosine_similarity([embeddings[-1]], np.array(pred_main['enc_sents'].to_numpy().tolist()))[0]

In [33]:
thresh = 0.6
idx = pd.DataFrame({'sims':sims}).query('sims>@thresh').sort_values(by='sims', ascending=False).index
main_sim_df = pred_main[['sentence', 'ttp', 'pred_str_tech']].loc[idx]

In [34]:
main_sim_df.explode('ttp')['ttp'].value_counts()

ttp
T1003.001    6
T1106        3
T1055.012    2
T1027        2
T1057        1
T1218.011    1
T1119        1
T1041        1
T1070        1
T1003.007    1
T1055.008    1
T1564.010    1
T1055        1
T1055.009    1
Name: count, dtype: int64

## сколько и какие пересекают грань

In [35]:
(pred_main['proba_tech'].map(lambda x: x[idx_cls])>proba).mean()

TypeError: only integer scalar arrays can be converted to a scalar index

In [64]:
import pandas as pd
sel_true = pred_main['ttp'].map(lambda x: ttp in x)
with pd.option_context('display.max_colwidth', 500):
    display(pred_main.loc[(pred_main['proba_tech'].map(lambda x: x[idx_cls])>proba), ['ttp', 'sentence']].head())

,ttp,sentence
182,[T1003.002],A number of tools can be used to retrieve the SAM file through in-memory techniques:
183,[T1003.002],"Alternatively, the SAM can be extracted from the Registry with Reg:"
184,[T1003.002],Creddump7 can then be used to process the SAM database locally to retrieve hashes.
252,[T1003.004],Reg can be used to extract from the Registry. Mimikatz can be used to extract secrets from memory.
382,[T1555.005],Adversaries may acquire user credentials from password managers by extracting the master password and/or plain-text credentials from memory. Adversaries may extract credentials from memory via [Exploitation for Credential Access].

## предсказания

In [36]:
(ttp_df['proba_ttp'].map(lambda x: x[mlb_ttp.transform([[ttp]]).argmax()])>0.049).mean()

NameError: name 'ttp_df' is not defined

## статистика по словам

In [ ]:
index = 31728

In [ ]:
ttp_df.iloc[index]['sentence']

In [ ]:
with pd.option_context('display.max_columns', 100):
    # display(exp.text_explain(idx[N]))
    display(exp.text_explain(index, exp_type='algo'))

In [ ]:
exp.cls_explain(ttp, k=10)

## близкие тексты

In [ ]:
from src.interpret.close_k_feat import select_k_neigh

comp_df, _ = select_k_neigh(ttp_df, feat_ttp, k=6, idx=[index], target_col='ttp')

In [ ]:
with pd.option_context('display.max_colwidth', 200):
    display(comp_df.iloc[0:])

<div class='alert alert-info'>
В целом текст похож, не хватило cut-off 
</div>

## deepseek и подход изучаем

ниже дам предложение, классифицируй его как технику MITRE (https://attack.mitre.org/):
"access critical system resources, including the LSASS memory space"

In [75]:
pred_main.loc[pred_main.sentence.str.contains('similar'), 'ttp'].explode('ttp').value_counts()

ttp
T1027        11
T1140         7
T1036.005     7
T1574.002     4
T1057         4
             ..
T1606.001     1
T1608.005     1
T1562.010     1
T1218.012     1
T1560.003     1
Name: count, Length: 89, dtype: int64

# Качество

Тут с FP границей на 1%, из-за того метрика так просела

In [20]:
pred_main = pred_main.assign(target=df.target_ttp)

In [21]:

from sklearn.metrics import (average_precision_score, log_loss, confusion_matrix,
                            precision_recall_fscore_support, f1_score)

p_val_micro, r_val_micro, f1_val_micro, sup = precision_recall_fscore_support(np.array(pred_main['target'].values.tolist()), 
                                                    np.array(pred_main['pred_tech'].values.tolist()), average='micro')
p_val_macro, r_val_macro, f1_val_macro, sup = precision_recall_fscore_support(np.array(pred_main['target'].values.tolist()), 
                                                    np.array(pred_main['pred_tech'].values.tolist()), average='macro')

f1_val_micro, f1_val_macro

(0.6820146066563898, 0.6145193913944036)